/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CharactersRouteImport } from './routes/characters'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as CreateRouteImport } from './routes/create'
import { Route as ImportRouteImport } from './routes/import'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LorebooksRouteImport } from './routes/lorebooks'
import { Route as MeRouteImport } from './routes/me'
import { Route as PersonasRouteImport } from './routes/personas'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WorldsRouteImport } from './routes/worlds'
import { Route as ApiGenerateRouteImport } from './routes/api/generate'
import { Route as CharacterIdRouteImport } from './routes/character.$id'
import { Route as LorebookIdRouteImport } from './routes/lorebook.$id'
import { Route as MemoriesIdRouteImport } from './routes/memories.$id'
import { Route as PersonaIdRouteImport } from './routes/persona.$id'
import { Route as PlayIdRouteImport } from './routes/play.$id'
import { Route as StoryIdRouteImport } from './routes/story.$id'
import { Route as WorldIdRouteImport } from './routes/world.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersRoute = CharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LorebooksRoute = LorebooksRouteImport.update({
  id: '/lorebooks',
  path: '/lorebooks',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonasRoute = PersonasRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldsRoute = WorldsRouteImport.update({
  id: '/worlds',
  path: '/worlds',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRoute = ApiGenerateRouteImport.update({
  id: '/api/generate',
  path: '/api/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const CharacterIdRoute = CharacterIdRouteImport.update({
  id: '/character/$id',
  path: '/character/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LorebookIdRoute = LorebookIdRouteImport.update({
  id: '/lorebook/$id',
  path: '/lorebook/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesIdRoute = MemoriesIdRouteImport.update({
  id: '/memories/$id',
  path: '/memories/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonaIdRoute = PersonaIdRouteImport.update({
  id: '/persona/$id',
  path: '/persona/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayIdRoute = PlayIdRouteImport.update({
  id: '/play/$id',
  path: '/play/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryIdRoute = StoryIdRouteImport.update({
  id: '/story/$id',
  path: '/story/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldIdRoute = WorldIdRouteImport.update({
  id: '/world/$id',
  path: '/world/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/characters': typeof CharactersRoute
  '/chats': typeof ChatsRoute
  '/create': typeof CreateRoute
  '/import': typeof ImportRoute
  '/library': typeof LibraryRoute
  '/lorebooks': typeof LorebooksRoute
  '/me': typeof MeRoute
  '/personas': typeof PersonasRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/worlds': typeof WorldsRoute
  '/api/generate': typeof ApiGenerateRoute
  '/character/$id': typeof CharacterIdRoute
  '/lorebook/$id': typeof LorebookIdRoute
  '/memories/$id': typeof MemoriesIdRoute
  '/persona/$id': typeof PersonaIdRoute
  '/play/$id': typeof PlayIdRoute
  '/story/$id': typeof StoryIdRoute
  '/world/$id': typeof WorldIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/characters': typeof CharactersRoute
  '/chats': typeof ChatsRoute
  '/create': typeof CreateRoute
  '/import': typeof ImportRoute
  '/library': typeof LibraryRoute
  '/lorebooks': typeof LorebooksRoute
  '/me': typeof MeRoute
  '/personas': typeof PersonasRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/worlds': typeof WorldsRoute
  '/api/generate': typeof ApiGenerateRoute
  '/character/$id': typeof CharacterIdRoute
  '/lorebook/$id': typeof LorebookIdRoute
  '/memories/$id': typeof MemoriesIdRoute
  '/persona/$id': typeof PersonaIdRoute
  '/play/$id': typeof PlayIdRoute
  '/story/$id': typeof StoryIdRoute
  '/world/$id': typeof WorldIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/characters': typeof CharactersRoute
  '/chats': typeof ChatsRoute
  '/create': typeof CreateRoute
  '/import': typeof ImportRoute
  '/library': typeof LibraryRoute
  '/lorebooks': typeof LorebooksRoute
  '/me': typeof MeRoute
  '/personas': typeof PersonasRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/worlds': typeof WorldsRoute
  '/api/generate': typeof ApiGenerateRoute
  '/character/$id': typeof CharacterIdRoute
  '/lorebook/$id': typeof LorebookIdRoute
  '/memories/$id': typeof MemoriesIdRoute
  '/persona/$id': typeof PersonaIdRoute
  '/play/$id': typeof PlayIdRoute
  '/story/$id': typeof StoryIdRoute
  '/world/$id': typeof WorldIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/characters'
    | '/chats'
    | '/create'
    | '/import'
    | '/library'
    | '/lorebooks'
    | '/me'
    | '/personas'
    | '/search'
    | '/settings'
    | '/worlds'
    | '/api/generate'
    | '/character/$id'
    | '/lorebook/$id'
    | '/memories/$id'
    | '/persona/$id'
    | '/play/$id'
    | '/story/$id'
    | '/world/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/characters'
    | '/chats'
    | '/create'
    | '/import'
    | '/library'
    | '/lorebooks'
    | '/me'
    | '/personas'
    | '/search'
    | '/settings'
    | '/worlds'
    | '/api/generate'
    | '/character/$id'
    | '/lorebook/$id'
    | '/memories/$id'
    | '/persona/$id'
    | '/play/$id'
    | '/story/$id'
    | '/world/$id'
  id:
    | '__root__'
    | '/'
    | '/characters'
    | '/chats'
    | '/create'
    | '/import'
    | '/library'
    | '/lorebooks'
    | '/me'
    | '/personas'
    | '/search'
    | '/settings'
    | '/worlds'
    | '/api/generate'
    | '/character/$id'
    | '/lorebook/$id'
    | '/memories/$id'
    | '/persona/$id'
    | '/play/$id'
    | '/story/$id'
    | '/world/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CharactersRoute: typeof CharactersRoute
  ChatsRoute: typeof ChatsRoute
  CreateRoute: typeof CreateRoute
  ImportRoute: typeof ImportRoute
  LibraryRoute: typeof LibraryRoute
  LorebooksRoute: typeof LorebooksRoute
  MeRoute: typeof MeRoute
  PersonasRoute: typeof PersonasRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  WorldsRoute: typeof WorldsRoute
  ApiGenerateRoute: typeof ApiGenerateRoute
  CharacterIdRoute: typeof CharacterIdRoute
  LorebookIdRoute: typeof LorebookIdRoute
  MemoriesIdRoute: typeof MemoriesIdRoute
  PersonaIdRoute: typeof PersonaIdRoute
  PlayIdRoute: typeof PlayIdRoute
  StoryIdRoute: typeof StoryIdRoute
  WorldIdRoute: typeof WorldIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lorebooks': {
      id: '/lorebooks'
      path: '/lorebooks'
      fullPath: '/lorebooks'
      preLoaderRoute: typeof LorebooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personas': {
      id: '/personas'
      path: '/personas'
      fullPath: '/personas'
      preLoaderRoute: typeof PersonasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worlds': {
      id: '/worlds'
      path: '/worlds'
      fullPath: '/worlds'
      preLoaderRoute: typeof WorldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate': {
      id: '/api/generate'
      path: '/api/generate'
      fullPath: '/api/generate'
      preLoaderRoute: typeof ApiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/character/$id': {
      id: '/character/$id'
      path: '/character/$id'
      fullPath: '/character/$id'
      preLoaderRoute: typeof CharacterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lorebook/$id': {
      id: '/lorebook/$id'
      path: '/lorebook/$id'
      fullPath: '/lorebook/$id'
      preLoaderRoute: typeof LorebookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories/$id': {
      id: '/memories/$id'
      path: '/memories/$id'
      fullPath: '/memories/$id'
      preLoaderRoute: typeof MemoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persona/$id': {
      id: '/persona/$id'
      path: '/persona/$id'
      fullPath: '/persona/$id'
      preLoaderRoute: typeof PersonaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$id': {
      id: '/play/$id'
      path: '/play/$id'
      fullPath: '/play/$id'
      preLoaderRoute: typeof PlayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/$id': {
      id: '/story/$id'
      path: '/story/$id'
      fullPath: '/story/$id'
      preLoaderRoute: typeof StoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world/$id': {
      id: '/world/$id'
      path: '/world/$id'
      fullPath: '/world/$id'
      preLoaderRoute: typeof WorldIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CharactersRoute: CharactersRoute,
  ChatsRoute: ChatsRoute,
  CreateRoute: CreateRoute,
  ImportRoute: ImportRoute,
  LibraryRoute: LibraryRoute,
  LorebooksRoute: LorebooksRoute,
  MeRoute: MeRoute,
  PersonasRoute: PersonasRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  WorldsRoute: WorldsRoute,
  ApiGenerateRoute: ApiGenerateRoute,
  CharacterIdRoute: CharacterIdRoute,
  LorebookIdRoute: LorebookIdRoute,
  MemoriesIdRoute: MemoriesIdRoute,
  PersonaIdRoute: PersonaIdRoute,
  PlayIdRoute: PlayIdRoute,
  StoryIdRoute: StoryIdRoute,
  WorldIdRoute: WorldIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
